### PR TITLE
Use tools provider

### PR DESCRIPTION
**Pull request by hinerm**
Update the JavaCompiler to first try the compiler returned by ToolsProvider - which avoids a hard dependency on javac.

### CODE REVIEW

**Comment by hinerm** [comment]
ScriptEditor compilation behavior:

Java 7
* minimaven.jar updated: *compilation successful*
* tools.jar and java.jar removed: *compilation successful*

Java 8
* minimaven.jar updated: ***compilation FAILED***
* tools.jar and java.jar removed: *compilation successful*

**Comment by hinerm** [comment]
Note that the failure comes because the java6 javac is picked up as *the* tools java compiler, even in Java8. So we need to kill our javac fork

**Comment by hinerm** [comment]
I was hoping that we could arrange things so the javac fork's compiler is picked up after any system java. I was hoping this would be possible with service or tool priorities, but it looks like the compiler tool is the exact same class in each case. So whichever is loaded first will win, and it seems like preference is given to the `/jars` on the classpath over system jars.

So to preserve javac and avoid breaking existing Java 6 installations we would have to load system classes first.

**Comment by ctrueden** [comment]
> So to preserve javac and avoid breaking existing Java 6 installations we would have to load system classes first.

Or shade the old java6 javac to a different package prefix.

But let's not. :stuck_out_tongue_closed_eyes:

**Comment by hinerm** [comment]
>Luckily, the BuildEnvironment already has verbose and debug flags

@ctrueden thanks for pointing this out. I [added a signature](https://github.com/scijava/minimaven/commit/a449c46b6948b19665c71ee7f79987af4f38955f) and logic to use these variables more liberally.

**Comment by ctrueden** [comment]
Thanks @hinerm! :bear:

**Pull request merged**
